FROM python:3.10.5-slim as builder

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src pyproject.toml ./
RUN pip install --editable .

ENTRYPOINT [ "panos-worker" ]
CMD [ "run" ]